# Generated by Django 5.0.6 on 2024-07-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_worktype_stage'),
        ('stages', '0003_stage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktype',
            name='stage',
        ),
        migrations.AddField(
            model_name='worktype',
            name='stages',
            field=models.ManyToManyField(related_name='work_types', to='stages.stage'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='description',
            field=models.TextField(),
        ),
    ]
