# Generated by Django 5.0.6 on 2024-07-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_stage_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stages/'),
        ),
    ]
